# Generated by Django 5.0.1 on 2024-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_category",
                    models.CharField(max_length=30, verbose_name="Vehicle Category"),
                ),
            ],
            options={
                "verbose_name": "Vehicle Category",
                "verbose_name_plural": "Vehicle Categories",
            },
        ),
    ]
