# Generated by Django 5.0.1 on 2024-02-03 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_classification",
                    models.CharField(
                        max_length=30, verbose_name="Vehicle Classification"
                    ),
                ),
                (
                    "vehicle_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Vehicles.vehiclecategory",
                        verbose_name="Vehicle Category",
                    ),
                ),
            ],
        ),
    ]
