# Generated by Django 5.0.1 on 2024-02-03 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicles", "0002_vehicleclassification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleclassification",
            options={
                "verbose_name": "Vehicle Classification",
                "verbose_name_plural": "Vehicle Classifications",
            },
        ),
        migrations.AlterField(
            model_name="vehicleclassification",
            name="vehicle_category",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Vehicles.vehiclecategory",
                verbose_name="Vehicle Category",
            ),
        ),
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_plate_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Plate Number"
                    ),
                ),
                (
                    "vehicle_classification",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Vehicles.vehicleclassification",
                        verbose_name="Vehicle Classification",
                    ),
                ),
                (
                    "vehicle_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vehicle Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
    ]
