# Generated by Django 5.0.1 on 2024-02-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicles", "0003_alter_vehicleclassification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleRFID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_rfid",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Vehicle RFID Code"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Vehicles.vehicles",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle RFID",
                "verbose_name_plural": "Vehicle RFIDs",
            },
        ),
    ]
