# Generated by Django 5.0.1 on 2024-02-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicles", "0004_vehiclerfid"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicles",
            name="vehicle_image",
            field=models.ImageField(
                default="vehicle_pics/vehicle.png", upload_to="vehicle_pics"
            ),
        ),
    ]
