# Generated by Django 5.0.1 on 2024-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicles", "0005_vehicles_vehicle_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicles",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
