# Generated by Django 5.0.1 on 2024-05-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
