# Generated by Django 5.0.1 on 2024-05-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0002_alter_conversation_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="body",
            field=models.TextField(default=""),
        ),
    ]
