# Generated by Django 5.0.1 on 2024-02-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Vehicles", "0005_vehicles_vehicle_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_in", models.DateTimeField(null=True, verbose_name="Time In")),
                ("time_out", models.DateTimeField(null=True, verbose_name="Time Out")),
                (
                    "vehicle_rfid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Vehicles.vehiclerfid",
                        verbose_name="Vehicle RFID Code",
                    ),
                ),
            ],
        ),
    ]
