# Generated by Django 5.0.1 on 2024-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnregisteredParking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_rfid",
                    models.CharField(
                        max_length=32, verbose_name="Unregistered Vehicle RFID Code"
                    ),
                ),
                ("time_in", models.DateTimeField(null=True, verbose_name="Time In")),
                ("time_out", models.DateTimeField(null=True, verbose_name="Time Out")),
            ],
        ),
    ]
