# Generated by Django 5.0.1 on 2024-02-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0002_unregisteredparking"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoveredParkingAreas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        max_length=16, verbose_name="Covered Parking Area"
                    ),
                ),
                ("max_parking", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
