# Generated by Django 5.0.1 on 2024-02-10 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0003_coveredparkingareas"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoveredParkingAreas",
            new_name="CoveredParkingArea",
        ),
    ]
