# Generated by Django 5.0.1 on 2024-02-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0004_rename_coveredparkingareas_coveredparkingarea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coveredparkingarea",
            name="area",
            field=models.CharField(
                max_length=16, unique=True, verbose_name="Covered Parking Area"
            ),
        ),
    ]
