# Generated by Django 5.0.1 on 2024-02-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0006_alter_coveredparkingarea_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoveredParking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_area", models.PositiveSmallIntegerField()),
                ("state", models.BooleanField(default=False)),
                ("time", models.DateTimeField(verbose_name="Time in")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Parking.coveredparkingarea",
                        verbose_name="Covered Parking",
                    ),
                ),
            ],
        ),
    ]
