# Generated by Django 5.0.1 on 2024-03-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0007_coveredparking"),
        ("Users", "0013_alter_profile_user_department_and_more"),
        ("Vehicles", "0005_vehicles_vehicle_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualEntryParking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crossing_time",
                    models.DateTimeField(null=True, verbose_name="Crossing Times"),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.identity",
                        verbose_name="Identity",
                    ),
                ),
                (
                    "vehicle_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Vehicles.vehiclecategory",
                        verbose_name="Vehicle Category",
                    ),
                ),
            ],
        ),
    ]
