# Generated by Django 5.0.1 on 2024-03-01 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0008_manualentryparking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manualentryparking",
            options={
                "verbose_name": "Manual Entry",
                "verbose_name_plural": "Manual Entries",
            },
        ),
    ]
