# Generated by Django 5.0.1 on 2024-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0010_manualentryparking_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualentryparking",
            name="action",
            field=models.CharField(
                choices=[("entry", "Entry"), ("exit", "Exit")],
                default="entry",
                max_length=5,
            ),
        ),
    ]
