# Generated by Django 5.0.1 on 2024-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0011_alter_manualentryparking_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Setting keyword"
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=128, verbose_name="Setting value"),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
