# Generated by Django 5.0.1 on 2024-03-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parking", "0013_coveredparkingarea_area_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coveredparkingarea",
            name="area_image",
            field=models.ImageField(
                default="parking_pics/parking_area.png", upload_to="parking_pics"
            ),
        ),
    ]
