# Generated by Django 5.0.1 on 2024-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept_abbr",
                    models.CharField(
                        max_length=10, verbose_name="Department Abbreviation"
                    ),
                ),
                (
                    "dept_name",
                    models.CharField(max_length=30, verbose_name="Department Name"),
                ),
            ],
        ),
    ]
