# Generated by Django 5.0.1 on 2024-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0002_rename_departments_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity_name",
                    models.CharField(max_length=30, verbose_name="Identity Name"),
                ),
            ],
        ),
    ]
