# Generated by Django 5.0.1 on 2024-02-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Users", "0004_delete_department_delete_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept_abbr",
                    models.CharField(
                        default="OTHERS",
                        max_length=10,
                        unique=True,
                        verbose_name="Department Abbreviation",
                    ),
                ),
                (
                    "dept_name",
                    models.CharField(
                        default="Others", max_length=30, verbose_name="Department Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity_name",
                    models.CharField(
                        default="Student",
                        max_length=30,
                        unique=True,
                        verbose_name="Identity Name",
                    ),
                ),
            ],
        ),
    ]
