# Generated by Django 5.0.1 on 2024-02-02 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0006_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_department",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Users.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_identity",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Users.identity",
                verbose_name="Role",
            ),
        ),
    ]
