# Generated by Django 5.0.1 on 2024-02-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0010_profile_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="dept_name",
            field=models.CharField(max_length=50, verbose_name="Department Name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_image",
            field=models.ImageField(
                default="profile_pics/profile.png", upload_to="profile_pics"
            ),
        ),
    ]
