# Generated by Django 5.0.1 on 2024-02-03 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0011_alter_department_dept_name_alter_profile_user_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="identity",
            options={"verbose_name": "Identity", "verbose_name_plural": "Identities"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
    ]
