# Generated by Django 5.0.1 on 2024-02-03 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0012_alter_department_options_alter_identity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_department",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Users.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_identity",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Users.identity",
                verbose_name="Role",
            ),
        ),
    ]
