# Generated by Django 5.0.1 on 2024-03-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0014_alter_profile_user_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_contact_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Contact Number"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_university_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Student/Employee Number",
            ),
        ),
    ]
